# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit fastsae.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center")
library(fastsae)


## ----load_and_fit-------------------------------------------------------------
library("fastsae")
data("sim_area")
sim_area$prov <- rep(paste0("Prov_", 1:6), each = 7)
sim_area$pop <- round(runif(nrow(sim_area), 15000, 45000))

# Construct row-standardized spatial proximity matrix
coords <- cbind(sim_area$x_coord, sim_area$y_coord)
dists <- as.matrix(dist(coords))
W <- (dists < quantile(dists, 0.18)) * 1
diag(W) <- 0
rs <- rowSums(W); rs[rs == 0] <- 1; W_std <- W / rs

# Fit Frequentist and Bayesian Models
fit_fh <- eblup_fh(y_gaussian ~ x1 + x2, vardir = "vardir",
  data = sim_area, method = "REML", print_result = FALSE)
fit_sfh <- eblup_sfh(y_gaussian ~ x1 + x2, vardir = "vardir",
  domain = "area", W = W_std, data = sim_area,
  method = "REML", print_result = FALSE)
fit_beta <- hb_area(y_beta ~ x1 + x2, vardir = "vardir",
  data = sim_area, family = "beta", spatial = "bym2",
  W = W, print_result = FALSE)


## ----compare_models-----------------------------------------------------------
comp <- compare_sae(fit_fh, fit_sfh, names = c("FH", "SFH"))
comp$metrics[c(1, 2, 4, 6, 8, 9), ]


## ----benchmark----------------------------------------------------------------
bm <- benchmark_sae(fit_fh, national_target = 0.50, group = "prov",
  weight = "pop", method = "ratio", type = "mean")
head(bm[, c("domain", "group", "original", "benchmarked", "rel_adjustment_pct")], 4)


## ----reliability--------------------------------------------------------------
flags <- add_reliability_flags(fit_beta, thresholds = c(20, 30))
table(flags$reliability)


## ----diagplot, fig.cap = "Model diagnostic panels generated via autoplot.", fig.width=7, fig.height=4.5, fig.path="figures/"----
diag_beta <- diagnose(fit_beta)
autoplot(diag_beta)

