# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.eblup_core <- function(Xall, yall, vardirall, method = "REML", maxiter = 100L, precision = 1e-4) {
    .Call(`_fastsae_eblup_core`, Xall, yall, vardirall, method, maxiter, precision)
}

.eblup_stfh_core <- function(X, y, vardir, proxmat, D, Tt, model = "ST", maxiter = 100L, precision = 1e-4, sigma21_start = -1.0, rho1_start = 0.5, sigma22_start = -1.0, rho2_start = 0.5) {
    .Call(`_fastsae_eblup_stfh_core`, X, y, vardir, proxmat, D, Tt, model, maxiter, precision, sigma21_start, rho1_start, sigma22_start, rho2_start)
}

.pbmse_stfh <- function(X, y, vardir, proxmat, D, Tt, model = "ST", maxiter = 100L, precision = 1e-4, B = 100L, n_threads = 0L, seed = -1L) {
    .Call(`_fastsae_pbmse_stfh`, X, y, vardir, proxmat, D, Tt, model, maxiter, precision, B, n_threads, seed)
}

.eblup_bhf_cpp <- function(selectdom, dom, Xs, meanxpop, ys, popnsize, betaest, upred) {
    .Call(`_fastsae_eblup_bhf_cpp`, selectdom, dom, Xs, meanxpop, ys, popnsize, betaest, upred)
}

.seblup_core <- function(Xall, yall, vardirall, Wall, method = "REML", maxiter = 100L, precision = 1e-4, only_core = FALSE) {
    .Call(`_fastsae_seblup_core`, Xall, yall, vardirall, Wall, method, maxiter, precision, only_core)
}

.seblup_npbmse <- function(X, y, vardir, W, method = "REML", maxiter = 100L, precision = 1e-4, B = 100L, n_threads = 0L, max_attempts_factor = 5L, seed = -1L) {
    .Call(`_fastsae_seblup_npbmse`, X, y, vardir, W, method, maxiter, precision, B, n_threads, max_attempts_factor, seed)
}

.seblup_pbmse <- function(X, y, vardir, W, method = "REML", maxiter = 100L, precision = 1e-4, B = 100L, n_threads = 0L, seed = -1L) {
    .Call(`_fastsae_seblup_pbmse`, X, y, vardir, W, method, maxiter, precision, B, n_threads, seed)
}

